apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact
  labels:
    app: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: contact
      labels:
        app: myapp
    spec:
      containers:
      - name: contact
        image: azlanirshad/contact:1
  selector:
    matchLabels:
      app: myapp  

